version: "3"
services:
  back:
    volumes:
      - ./back:/back
      - ./data/captures:/back/captures
      - /back/node_modules
    ports:
      - 3001:3001
  front:
    environment:
      - PORT=9000
    volumes:
      - ./front/app:/front/app
      - /front/app/node_modules
    ports:
      - 3000:80
      - 9000:9000