version: "3"
services:
  back:
    volumes:
      - ./data/captures:/back/captures
  front:
    environment:
      - NODE_ENV=production
    ports:
      - 8080:80
    command: >
     sh -c "npm run prod &&
            nginx -g 'daemon off;'"